:sparkles: 와이드뷰 배포 (보안 그룹 수정)

diff --git a/.github/workflows/blue-green-main-dev-deploy.yml b/.github/workflows/blue-green-main-dev-deploy.yml
--- a/.github/workflows/blue-green-main-dev-deploy.yml
+++ b/.github/workflows/blue-green-main-dev-deploy.yml
@@ -74,6 +74,12 @@ jobs:
             echo "Error: SSH_PRIVATE_KEY is not set!"
             exit 1
           fi
+          
+          # SERVER_HOST가 설정되지 않았을 때 에러 처리
+          if [ -z "$SERVER_HOST" ]; then
+            echo "Error: SERVER_HOST is not set!"
+            exit 1
+          fi
   
           echo "SERVER_HOST=$SERVER_HOST" >> $GITHUB_ENV
           ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts       
