:sparkles: 와이드뷰 배포....

diff --git a/.github/workflows/blue-green-main-dev-deploy.yml b/.github/workflows/blue-green-main-dev-deploy.yml
--- a/.github/workflows/blue-green-main-dev-deploy.yml
+++ b/.github/workflows/blue-green-main-dev-deploy.yml
@@ -64,10 +64,16 @@ jobs:
           echo "Target Group ARN: $TARGET_GROUP_ARN"
           echo "Current Port: $CURRENT_PORT"
           echo "New Port: $NEW_PORT"
-  
+          
           if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
             # main 브랜치: Blue-Green 타겟 그룹 설정
-            CURRENT_TARGET_GROUP_ARN=$(aws elbv2 describe-listeners --listener-arn ${{ secrets.LISTENER_ARN }} --query "Listeners[0].DefaultActions[0].TargetGroupArn" --output text)
+            CURRENT_TARGET_GROUP_ARN=$(aws elbv2 describe-listeners --listener-arn ${{ secrets.LISTENER_ARN }} --query "Listeners[0].DefaultActions[0].TargetGroupArn" --output text --debug)
+
+            # 오류 확인
+            if [ -z "$CURRENT_TARGET_GROUP_ARN" ]; then
+              echo "Error: Failed to retrieve Target Group ARN"
+              exit 1
+            fi
 
             if [ "$CURRENT_TARGET_GROUP_ARN" == "${{ secrets.BLUE_TARGET_GROUP_ARN }}" ]; then
               CURRENT_PORT=3000
@@ -81,7 +87,13 @@ jobs:
 
           elif [[ "${{ github.ref }}" == "refs/heads/wideview-deploy" ]]; then
             # dev(wideview-deploy) 브랜치: Dev Blue-Green 타겟 그룹 설정
-            CURRENT_TARGET_GROUP_ARN=$(aws elbv2 describe-listeners --listener-arn ${{ secrets.DEV_LISTENER_ARN }} --query "Listeners[0].DefaultActions[0].TargetGroupArn" --output text)
+            CURRENT_TARGET_GROUP_ARN=$(aws elbv2 describe-listeners --listener-arn ${{ secrets.DEV_LISTENER_ARN }} --query "Listeners[0].DefaultActions[0].TargetGroupArn" --output text --debug)
+
+            # 오류 확인
+            if [ -z "$CURRENT_TARGET_GROUP_ARN" ]; then
+              echo "Error: Failed to retrieve Target Group ARN"
+              exit 1
+            fi
 
             if [ "$CURRENT_TARGET_GROUP_ARN" == "${{ secrets.DEV_BLUE_TARGET_GROUP_ARN }}" ]; then
               CURRENT_PORT=3000
